#+LaTeX_HEADER: \usepackage[parameters]{listings}
#+LaTeX_HEADER: \usepackage{listings}
#+LaTeX_HEADER: \usepackage[english]{babel}
#+LaTeX_HEADER: \usepackage{color} 
#+LaTeX_HEADER: \usepackage[section]{placeins} 
#+LaTeX_HEADER: \definecolor{mygreen}{RGB}{28,172,0} 
#+LaTeX_HEADER: \definecolor{mylilas}{RGB}{170,55,241}
#+LaTeX_CLASS_OPTIONS: [listings, listings-bw, listings-color, listings-sv]
#+LATEX_HEADER: \usepackage[margin=1.25in]{geometry}
#+OPTIONS: toc:nil

#+TITLE: Understanding The Relationship Between Microscopic Mechanisms and Continuum Description of Diffusion
#+AUTHOR: MSE 6270: Introduction to Atomistic Simulations @@latex:\\@@ Homework #5 @@latex:\\\\@@Yosyp Schwab
#+EMAIL: ys4ea@virginia.edu
#+DATE: March 22, 2018

* Question 1
Using the same FCC crystal that you used in homework #4 (7×7×7 unit
 cells), but build it with the lattice parameter afcc = 5.78 Å that is
 based on the experimental molar volume of liquid Ar at the melting
 temperature and 1 atm pressure.

 Perform a simulation at constant volume and temperature T = 1.5Tm,
 where Tm is the melting you found in homework #4.

 Run the simulations for a time sufficient to collect data for the
 calculation of the diffusion coefficient.



From HW#4 the melting temperature of Ar at pressure of 1 atm and molar
volume of 24.6 $\frac{cm^3}{mole}$ was $T_{m} = 92 K$. An FCC crystal with
7x7x7 unite cells was constructed with lattice parameter $a_{fcc} =
5.78 A" and simulated at constant volume and temperature $T = 1.5
T_{m} = 138 K$. 

\begin{equation}
a = \sqrt[3]{4 \frac{V_m}{Av}} = 5.467 A
\end{equation}

#+CAPTION: 
#+NAME: fig:
file:figures/q6-quad.png

* Question 2

To calculate the mean square displacement 

#+CAPTION: 
#+NAME: fig:q2msd
file:figures/q2-msd.png

* Question 3

#+CAPTION: 
#+NAME: fig:q2msd
file:figures/q3-msd3d.png

#+CAPTION: 
#+NAME: fig:q2msd
file:figures/q2-msd3d.png


* References
1. The argon melting curve to very high pressures. C-S. Zha, R. Boehler, D. A. Young, M. Ross. The Journal of Chemical Physics 85, 1034 (1986)

2. Extended and accurate determination of the melting curves of argon, helium ice (H_{2}O), and hydrogen (H_2). F. Datchu, P. Laubeyre, R. LeToullec. Physical Review B 61, 6535 (2000)
f

 
% Literature source for Argon
% at T = 84 K, 1.53 10e-5 cm^2/sec 
% https://aip.scitation.org/doi/abs/10.1063/1.1700899
%
% at T = 295 K and 42 kPa, 0.423 cm^2/sec
% https://journals.aps.org/pr/pdf/10.1103/PhysRev.72.1256

% at T = K and 87 kPa, 2.07 10e-5 cm^2/sec

% Unit conversion:
% 1 Angstrom^2/ps = 10e-4 cm^2/sec = 10e-8 m^2/s

